# == == == OPTIONS == == ==
set -g mouse on
set-option -g allow-rename off

# == == == BINDS == == ==
# map prefix to C-Escape
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# splits to | -_
bind | split-window -h
bind \\ split-window -h
bind _ split-window -v
bind - split-window -v
unbind '"'
unbind %

# alt arrow for pane nav
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf

# == == == THEME == == == 
set -g status-style bg=default
set-option -g status-right "%Y-%m-%d %H:%M"

# status colors per-host :3
%if "#{==:#{host},pantheon}"
    set -g window-status-current-style bg=red,fg=black
    set -g status-right-style          bg=red,fg=black
%elif "#{==:#{host},zephyr}"
    set -g window-status-current-style bg=red,fg=black
    set -g status-right-style          bg=red,fg=black
%elif "#{==:#{host},cerberus}"
    set -g window-status-current-style bg=green,fg=black
    set -g status-right-style          bg=green,fg=black
%else
    set -g window-status-current-style bg=yellow,fg=black
    set -g status-right-style          bg=yellow,fg=black
%endif
