export let palette = #{
	"bg": "#131200",
	"fg": "#f51c99",
	// black
	"color0"  : "#272822",
	"color8"  : "#75715e",
	// red
	"color1"  : "#f51c99",
	"color9"  : "#f92672",
	// green
	"color2"  : "#1cf599",
	"color10" : "#a6e22e",
	// yellow
	"color3"  : "#f5991c",
	"color11" : "#f4bf75",
	// blue
	"color4"  : "#1c99f5",
	"color12" : "#66d9ef",
	// magenta
	"color5"  : "#991cf5",
	"color13" : "#ae81ff",
	// cyan
	"color6"  : "#00ffff",
	"color14" : "#a1efe4",
	// white
	"color7"  : "#f8f8f2",
	"color15" : "#f9f8f5",
};
