# {% if SYSTEM.hostname == "zephyr" %}
#<yolk> eval "$(/opt/homebrew/bin/brew shellenv)"
#<yolk> # {# replace_between(`"`, `@`, secrets::get("mpd")) #} 
#<yolk> export MPD_HOST="@TODO DYNDNS"
# {% end %}

# {% if SYSTEM.hostname == "pantheon" %}
#<yolk> export MOZ_ENABLE_WAYLAND=1
#<yolk> export QT_QPA_PLATFORM=wayland
#<yolk> export ELECTRON_OZONE_PLATFORM_HINT=auto
#<yolk> export GTK_THEME=Adwaita:dark
#<yolk> # export MANGOHUD=1

#<yolk> export MPD_HOST="@mpd"
#<yolk> # good lord what's going on in here
#<yolk> export PATH=$PATH:"$HOME/.cargo/bin:$PATH:$HOME/bin"
# {% end %}


export EDITOR=`which nvim`
