update_interval = "30mins"
digital_ocean_token = ""  # {< rin(`"`, secrets::get("DO_ddns_token")) >}

dry_run = false
collect_stats = true
database_path = "/home/hecate/.config/ddns/dyndns_stats_db.sqlite"
enable_web = false

ipv6 = true

[[domains]]
name = "hecate.pink"

[[domains.records]]
type = "AAAA"
name = "canonical-hostname" # {< rin(`"`, SYSTEM.hostname) >}
