music_directory     "~/music/mp3"
playlist_directory  "~/music/mpd/playlists"

db_file   "~/music/mpd/db"
pid_file  "~/music/mpd/pid"
bind_to_address "~/music/mpd/socket"
bind_to_address "@mpd"

bind_to_address	"any"
port            "6600"

# {# replace_between(`"`, `@`, secrets::get("mpd")) #}
password "@read,add,player,control"
local_permissions "read,add,player,control,admin"

audio_output {
  type  "pipewire"
  name  "PipeWire Sound Server"
}

audio_output {
  type    "fifo"
  name    "my_fifo"
  path    "/tmp/mpd.fifo"
  format  "44100:16:2"
}

audio_output {
  type  "httpd"
  bind_to_address "192.168.0.3"
  port "6601"
  dscp_class "CS3"
  encoder "vorbis"
  name "apollo?"
}
